Upgraded rust nightly version in CI
Otherwise we get:

```text
error[E0428]: the name `_` is defined multiple times
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerocopy-0.8.27/src/byteorder.rs:497:9
    |
497 |           const _: () = unsafe {
    |           ^^^^^^^^^^^^^^^^^^^^ `_` redefined here
...
734 | / define_type!(
735 | |     A,
736 | |     "A 64-bit unsigned integer",
737 | |     U64,
...   |
749 | |     [U128]
750 | | );
    | |_- in this macro invocation
    |
   ::: /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerocopy-0.8.27/src/util/macros.rs:431:9
    |
431 |           const _: () = {
    |           ------------- previous definition of the value `_` here
    |
    = note: `_` must be defined only once in the value namespace of this module
    = note: this error originates in the macro `define_type` (in Nightly builds, run with -Z macro-backtrace for more info)
```