Implement TryFrom<SysCallReg> instead of TryFromScallReg
Now that SysCallReg lives in a different crate than the syscall type
formatting code, the compilation breaks because it no longer knows
whether TryFrom<SysCallReg> will be implemented, causing a potential
conflict between the blanket implementation of TryFromSysCallReg,
and the explicit implementations.

Implementing the TryFrom traits fixes the conflict.

i.e. this commit fixes compilation errors like:

```
error[E0119]: conflicting implementations of trait `host::syscall::type_formatting::TryFromSyscallReg` for type `nix::fcntl::OFlag`
   --> main/host/syscall/type_formatting.rs:154:1
    |
17  | impl<T: TryFrom<SysCallReg>> TryFromSyscallReg for T {
    | ---------------------------------------------------- first implementation here
...
154 | impl TryFromSyscallReg for nix::fcntl::OFlag {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `nix::fcntl::OFlag`
    |
    = note: upstream crates may add a new impl of trait `std::convert::From<shadow_shim_helper_rs::syscall_types::SysCallReg>` for type `nix::fcntl::OFlag` in future versions
```