Fixed binding modifier errors
The default binding mode was changed to "ref" in rust 2021, and now in
rust 2024 it's an error to use the `ref` binding modifier when the
binding mode is already "ref".

For example:

```text
error: binding modifiers may only be written when the default binding mode is `move`
   --> lib/tcp/src/buffer.rs:347:27
    |
347 |             Segment::Data(ref data) => data.len().try_into().unwrap(),
    |                           ^^^ binding modifier not allowed under `ref` default binding mode
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/match-ergonomics.html>
```