Make clippy happy
Somehow the cbindgen update caused clippy to raise an error due to:

https://rust-lang.github.io/rust-clippy/master/index.html#field_reassign_with_default

```text
error: field assignment outside of initializer for an instance created with Default::default()
   --> lib/shadow-build-common/src/lib.rs:107:9
    |
107 |         config.language = cbindgen::Language::C;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: consider initializing the variable with `cbindgen::Config { language: cbindgen::Language::C, line_length: 100, documentation_style: cbindgen::DocumentationStyle::C99, ..Default::default() }` and removing relevant reassignments
   --> lib/shadow-build-common/src/lib.rs:106:9
    |
106 |         let mut config = cbindgen::Config::default();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```