Removed duplicate "Profiling" page from book
This duplicate causes mdbook to fail as of version 0.4.48.

```text
Error: -01 01:03:04 [ERROR] (mdbook::utils): Error: Summary parsing failed for file="/home/runner/work/docs/docs/shadow/mdbook/../docs/SUMMARY.md"
Error: -01 01:03:04 [ERROR] (mdbook::utils): 	Caused By: Duplicate file in SUMMARY.md: "profiling.md"
Error: Process completed with exit code 101.
```